#!/usr/bin/env bash
NDOCS_BIN="tools/NaturalDocs-1.52/NaturalDocs"

if [ ! -x "${NDOCS_BIN}" ]; then
    echo -en "Run from top-level xy directory.\n"
    exit 1
fi

OUT_DIR="docs/html"
PRJ_DIR="docs/prj"
SRC_DIR="src"

if [ ! -d "${OUT_DIR}" -o ! -d "${PRJ_DIR}" ]; then
    mkdir -p "${OUT_DIR}" "${PRJ_DIR}"
fi

echo -en "Generating ${OUT_DIR}... "
"${NDOCS_BIN}" -q -i "${SRC_DIR}" -p "${PRJ_DIR}" -o FramedHTML "${OUT_DIR}"
echo -en "done\n"
