#!/usr/bin/env bash
. ../resources/common.sh

VALGRIND=$(which valgrind)
if [ -z "${VALGRIND}" ]; then
    echo "missing valgrind"
    exit 1
fi

VG_SUPPRESSIONS="vg_suppressions"
VG_ARGS="--suppressions=${VG_SUPPRESSIONS} \
         --tool=memcheck --leak-check=full \
         --quiet"

TESTS=$(ls *_tests 2>/dev/null)
if [ -z "${TESTS}" ]; then
    echo "no tests built (*_tests)"
    exit 1
fi

start_display

for test in *_tests; do
    echo "--- ${test} --- "
    ${VALGRIND} ${VG_ARGS} ./${test} >/dev/null
done

stop_display

exit 0
